### ISSUE TITLE
Pezzo API is throwing 404

### ISSUE THREAD

**Issue by Wiz-Amit** [pezzolabs/examples#1]
I have tried to test without making any changes to the code. GenerateTask API call is throwing 404.

**Comment by arielweinberger** [comment]
Hi Amit, can you please provide detailed logs? It's impossible to assist without seeing those.

**Comment by Wiz-Amit** [comment]
## Steps to reproduce:
1. Clone this repo
2. Add `PEZZO_API_KEY` and `OPENAI_API_KEY` on `.env.local`
3. Run and test the task generator app
4. Create and publish a Prompt `GenerateTasks` with the following prompt on your pezzo account under `Development` environment
```
You are a talented task generator.

You'll help me generate tasks to achieve the following goal: "{goal}".
You must generate exactly {numTasks} tasks.

You must respond in valid JSON, strictly adhering to the following schema:

{
  tasks: string[];
}
```

## Expected Result
Should run successfully and show generated task

## Current Error

```
    data: {
      statusCode: 404,
      message: 'Cannot GET /api/prompts/deployment?name=GenerateTasks&environmentName=Development',
      error: 'Not Found'
    }
```

**Comment by Wiz-Amit** [comment]
Hi,
Could you please confirm if this repo is up to date and working as expected?

**Comment by arielweinberger** [comment]
Hi @Wiz-Amit, sorry for the late response! This repo is not in use anymore. We should mark it as archived.

We've recently release `v0.4.0` which is an overhaul and many things changed. My I suggest that you take a look at the [pezzolabs/pezzo](https://github.com/pezzolabs/pezzo) repo and take a look? We also have more elaborate documentation.

Also, feel free to ping me on [Discord](https://pezzo.cc/discord) and I'd love to hop on a session and learn about your use case. Of course, I'd be happy to help you get up and running too.
